# Travis CI build configuration config file.
language: php

python:
  - 5.6
# - 7

addons:
  hosts:
    - localhost
  apt:
    packages:
    # - drush # See: https://github.com/travis-ci/apt-package-whitelist/issues/1611
    - wget
    - realpath
    - tree
    - html2text

notifications:
  email:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   never   # options: [always|never|change] default: always

# Environment
sudo: false
env:
  global:
    - URL="http://$HOSTNAME:8080/"
    - COMPOSER_BIN_DIR=~/bin
    - DB_URL="mysql://root:@localhost/drupal"
    - PATH=${PATH//:\.\/node_modules\/\.bin/} # Fixes Travis bug: https://github.com/travis-ci/travis-ci/issues/4862

  matrix:
    - CORE=7 TEST_MODULE="postcodeanywhere" DOWNLOAD="postcodeanywhere"
    - CORE=7 TEST_MODULE="postcodeanywhere" DOWNLOAD="postcodeanywhere-7.x-1.x-dev"
  fast_finish: true # Don't wait for the allowed failures to build.

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
# - env
# - set -e # Fail build on first error.

install:
  - gem install mailcatcher && mailcatcher -v && echo 'sendmail_path="/usr/bin/env catchmail"' | tee -a "$(php --ini | grep "Loaded Configuration" | awk '{print $4}')"
  - composer global require drush/drush:dev-master drupal/coder && drush --version
  - drush qd --yes --server=$URL --no-server --watchdog --core=drupal-$CORE testsite && cd testsite/drupal-*
  - drush -vy dl $DOWNLOAD
  - drush -vy en $TEST_MODULE

before_script:
  - drush -v rs $URL &
  - phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer
  - html2text <(wget -O- --retry-connrefused $URL)
# - mysql -e 'create database drupal'

script:
  - phpcs -n --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt,md $(drush dd $TEST_MODULE)
  - drush core-requirements --severity=2 | grep -i error
  - phpunit .

after_success:
 - html2text <(curl http://localhost:1080)

after_failure:
 - drush status --full
 - drush core-requirements --severity=2
 - tree -d -L 6 # Print directory structure in the form of a tree.

after_script:
 - drush ws --full
 - html2text <(wget -qO- $URL)
