<?php

/**
 * @file
 *   Form settings per user
 *
 * @version
 *   $Id$
 *
 * @developers:
 *    Rafal Wieczorek <kenorb@gmail.com>
 */

/* Lookups of this postcode do not cost any credit */
define('PCA_TEST_PC', 'WR2 6NJ');

/**
 * Implementation of hook_menu().
 *
 */
function postcodeanywhere_menu() {
  $items['admin/settings/postcodeanywhere'] = array(
    'title' => 'Postcode Anywhere',
    'description' => 'Manage Postcode Anywhere plugin.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('postcodeanywhere_settings_form'),
    'access arguments' => array('administer postcodeanywhere'),
    'file' => 'postcodeanywhere.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 *
 */
function postcodeanywhere_perm() {
  $permissions = array(
    'administer postcodeanywhere',
    'use PHP for postcodeanywhere visibility',
  );
  
  return $permissions;
}

/**
 * Implementation of hook_form_alter().
 */
function postcodeanywhere_form_alter(&$form, $form_state, $form_id) {
  $forms = array_flip( is_string( $pca_forms = variable_get('pca_forms', array())) ? unserialize($pca_forms) : $pca_forms );
  unset($forms[0]);
  // drupal_set_message($form_id . ' - ' . print_r($forms, true)); // use it for testing purposes
  $page_match = FALSE;
  foreach ($forms as $pca_form_name) {
    if (substr($form_id, 0, strlen($pca_form_name)) == $pca_form_name) {
      $page_match = TRUE;
      break;
    }
  }

  if (!$page_match) {
    // check for path matches
    $pca_rules = variable_get('pca_page_visibility_rules', '');
    $pca_mode = variable_get('pca_page_visibility_mode', '');
      if ($pca_rules) {
        if ($pca_mode < 2) {
          $path = drupal_get_path_alias($_GET['q']);
          // Compare with the internal and path alias (if any).
          $page_match = drupal_match_path($path, $pca_rules);
          if ($path != $_GET['q']) {
            $page_match = $page_match || drupal_match_path($_GET['q'], $pca_rules);
          }
          // When $pca_mode has a value of 0, the block is displayed on
          // all pages except those listed in $block->pages. When set to 1, it
          // is displayed only on those pages listed in $pca_rules.
          $page_match = !($pca_mode xor $page_match);
        }
        else {
          $page_match = drupal_eval($pca_rules);
        }
      }
      else {
        $page_match = TRUE;
      }
  }

  if ($page_match) {
      postcodeanywhere_form_add_js(); // include postcodeanywhere JS file
  }
}

/**
 * Include postcodeanywhere js files
 */
function postcodeanywhere_form_add_js() {
  // load variables
  drupal_add_js("
      var pca_account_code = '". variable_get('pca_account_code', '') ."';
      var pca_licence = \"". variable_get('pca_licence', '') . "\";
      var pca_id_postcode_wrapper = \"". variable_get('pca_id_postcode_wrapper', '') . "\";
      var pca_id_input_postcode = \"". variable_get('pca_id_input_postcode', '') . "\";
      var pca_id_house_number = \"". variable_get('pca_id_house_number', '') . "\";
      var pca_id_property_name = \"". variable_get('pca_id_property_name', '') . "\";
      var pca_id_street = \"". variable_get('pca_id_street', '') . "\";
      var pca_id_city = \"". variable_get('pca_id_city', '') . "\";
      var pca_id_county = \"". variable_get('pca_id_county', '') . "\";
      var pca_id_country = \"". variable_get('pca_id_country', '') . "\";
      var pca_id_uk_value = '". variable_get('pca_id_uk_value', 226) . "';
      var pca_showAlert = ". variable_get('pca_showalert', 1) . "; 
      var pca_url = '". variable_get('pca_url', 'http://services.postcodeanywhere.co.uk/inline.aspx') ."';", 'inline');
  drupal_add_js(drupal_get_path('module', 'postcodeanywhere') . '/postcodeanywhere.js');
}

