<?php

/**
 * @file
 * Handles the postcodeanywhere hooks.
 */

/**
 * Implementation of hook_menu().
 */
function postcodeanywhere_menu() {
  $items = array();

  $items['admin/config/content/postcodeanywhere'] = array(
    'title' => 'Postcode Anywhere',
    'description' => 'Manage Postcode Anywhere settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('postcodeanywhere_settings_form'),
    'access arguments' => array('administer postcodeanywhere'),
    'file' => 'postcodeanywhere.admin.inc',
  );

  $items['postcodeanywhere/findbypostcode/%'] = array(
    'title' => 'Postcode Lookup',
    'description' => 'Lookup Address By PostCode.',
    'page callback' => 'postcodeanywhere_findbypostcode',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
  );

  $items['postcodeanywhere/retrievebyid/%'] = array(
    'title' => 'Address retrieval',
    'description' => 'Retrieve address by id.',
    'page callback' => 'postcodeanywhere_retrievebyid',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implementation of hook_permission().
 */
function postcodeanywhere_permission() {
  return array(
    'administer postcodeanywhere' => array(
      'title' => t('Administer postcode anywhere settings'), 
      'description' => t('Perform administration tasks for my module.'),
  ),
    'use PHP for postcodeanywhere visibility' => array(
      'title' => t('Administer postcode anywhere settings'), 
      'description' => t('Use PHP for postcodeanywhere visibility settings.'),
  ),
  );
}

/**
 * Implementation of hook_form_alter().
 */
function postcodeanywhere_form_alter(&$form, $form_state, $form_id) {

  // Check whether path matches one defined in postcodeanywhere settings.
  $postcodeanywhere_rules = variable_get('postcodeanywhere_page_visibility_rules', '');
  $postcodeanywhere_mode = variable_get('postcodeanywhere_page_visibility_mode', '');
  if ($postcodeanywhere_rules) {
    if ($postcodeanywhere_mode < 2) {
      $path = drupal_get_path_alias($_GET['q']);
      // Compare with the internal and path alias (if any).
      $page_match = drupal_match_path($path, $postcodeanywhere_rules);
      if ($path != $_GET['q']) {
        $page_match = $page_match || drupal_match_path($_GET['q'], $postcodeanywhere_rules);
      }
      // When $postcodeanywhere_mode has a value of 0, the block is displayed on
      // all pages except those listed in $block->pages. When set to 1, it
      // is displayed only on those pages listed in $postcodeanywhere_rules.
      $page_match = !($postcodeanywhere_mode xor $page_match);
    }
    else {
      $page_match = php_eval($postcodeanywhere_rules);
    }
  }
  else {
    $page_match = TRUE;
  }

  if ($page_match) {
    // include postcodeanywhere JS file after form is built
    $form['#after_build'][] = 'postcodeanywhere_form_after_build';
  }
}

/**
 * Implementation of #after_build function
 * Helper function to include postcodeanywhere js files after form is built
 */
function postcodeanywhere_form_after_build($form_element, &$form_state) {
  postcodeanywhere_form_add_js();
  return $form_element;
}

/**
 * Helper function to include postcodeanywhere js files.
 */
function postcodeanywhere_form_add_js($extra_settings = NULL) {
  static $pca_loaded = FALSE;

  // Don't allow to load the JS file twice
  if ($pca_loaded) {
    return;
  }

  $pca_loaded = TRUE;

  // Add postcodeanywhere settings to Drupal's global storage.
  $settings = array(
    'postcodeanywhere' => array(
      'account_code' => variable_get('postcodeanywhere_account_code', ''),
      'licence' => variable_get('postcodeanywhere_licence', ''),
      'id_wrapper' => variable_get('postcodeanywhere_id_wrapper', ''),
      'id_postcode' => variable_get('postcodeanywhere_id_postcode', ''),
      'id_lookup_button' => '#postcodeanywhere-lookup-button',
      'id_company' => variable_get('postcodeanywhere_id_company', ''),
      'id_company_wrapper' => variable_get('postcodeanywhere_id_company_wrapper', ''),
      'id_line1' => variable_get('postcodeanywhere_id_line1', ''),
      'id_line1_wrapper' => variable_get('postcodeanywhere_id_line1_wrapper', ''),
      'id_line2' => variable_get('postcodeanywhere_id_line2', ''),
      'id_line2_wrapper' => variable_get('postcodeanywhere_id_line2_wrapper', ''),
      'id_line3' => variable_get('postcodeanywhere_id_line3', ''),
      'id_line3_wrapper' => variable_get('postcodeanywhere_id_line3_wrapper', ''),
      'id_town' => variable_get('postcodeanywhere_id_town', ''),
      'id_town_wrapper' => variable_get('postcodeanywhere_id_town_wrapper', ''),
      'id_county' => variable_get('postcodeanywhere_id_county', ''),
      'id_county_wrapper' => variable_get('postcodeanywhere_id_county_wrapper', ''),
      'id_country' => variable_get('postcodeanywhere_id_country', ''),
      'id_country_uk_value' => variable_get('postcodeanywhere_id_country_uk_value', 'GB'),
      'submit_label_value' => variable_get('postcodeanywhere_submit_label_value', 'Find Address'),
      'showAlert' => variable_get('postcodeanywhere_showalert', 1),
      'url' => variable_get('postcodeanywhere_url', 'http://services.postcodeanywhere.co.uk/inline.aspx'),
    ),
  );

  // Add extra settings to JS setting value
  if ($extra_settings && is_array($extra_settings)) {
    foreach ($extra_settings as $key => $value) {
      $settings['postcodeanywhere'][$key] .= ',' . $value;

      // Set as already loaded, so don't try to load it again (e.g. hook_form_alter)
      $pca_loaded = TRUE;
    }
  }

  drupal_add_js($settings, 'setting'); // Append settings into JS file
  drupal_add_js(drupal_get_path('module', 'postcodeanywhere') . '/postcodeanywhere.js', 'file');
}

function postcodeanywhere_findbypostcode($postcode = "WR2 6NJ") {
  require_once(drupal_get_path('module', 'postcodeanywhere') . "/classes/PostcodeAnywhere_Interactive_FindByPostcode.class.inc");
  $licence_key = variable_get('postcodeanywhere_licence', '');

  try {
    $pa = new PostcodeAnywhere_Interactive_FindByPostcode($licence_key, $postcode, "");

    $pa->MakeRequest();
    if ($pa->HasData()) {
      $data = $pa->HasData();
    }
  }
  catch (Exception $e) {
    $data['error'] = $e->getMessage();
  }

  drupal_json_output($data);
}

function postcodeanywhere_retrievebyid($id) {
  require_once(drupal_get_path('module', 'postcodeanywhere') . "/classes/PostcodeAnywhere_Interactive_RetrieveById.class.inc");
  $licence_key = variable_get('postcodeanywhere_licence', '');

  // @todo Update this to a D7 db_select.
  $query = db_query("SELECT json FROM {postcodeanywhere_cache} WHERE udprn = :udprn", array(
      ':udprn' => $id,
  )
  );

  $data = $query->fetchField();

  if ($data) {
    echo $data;
    drupal_json_output();
  }
  else {
    try {
      $pa = new PostcodeAnywhere_Interactive_RetrieveById($licence_key, $id, "English", "");
      $pa->MakeRequest();
      if ($pa->HasData()) {
        $data = $pa->HasData();

        $record = array();
        $record['udprn'] = $id;
        $record['json'] = json_encode($data);
        $record['timestamp'] = time();
        drupal_write_record('postcodeanywhere_cache', $record);

      }
    }
    catch (Exception $e) {
      $data['error'] = $e->getMessage();
    }
    drupal_json_output($data);
  }
}
